version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - REDIS_URL=redis://redis:6379/0
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - RAILS_MAX_THREADS=5
      - CHAT_SYSTEM_DATABASE_PASSWORD=pass
    ports:
      - "3000:5000"
    volumes:
      - .:/app
    command: /app/startup.sh
    depends_on:
      - mysql
      - elasticsearch
      - redis

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
    ports:
      - "3307:3306"
    # volumes:
      # - mysql_data:/var/lib/mysql

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
    ports:
      - "9200:9200"

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"


# volumes:
#   mysql_data: